### ISSUE TITLE
temperature_generalTest_Kelvin seems to struggle

### ISSUE THREAD

**Issue by bluePlatinum** [bluePlatinum/KMCC#12]
Test Report:
Test Name:	temperature_generalTest_Kelvin
Test FullName:	KMCC.Model.unitClasses.Tests.temperatureTests.temperature_generalTest_Kelvin
Test Source:	****\KMCC\UnitTests\Model\unitClasses\temperatureTests.cs : line 36
Test Outcome:	Failed
Test Duration:	0:00:00,3802636

Result StackTrace:	at KMCC.Model.unitClasses.Tests.temperatureTests.temperature_generalTest_Kelvin() in ****\KMCC\UnitTests\Model\unitClasses\temperatureTests.cs:line 50
Result Message:	Assert.AreEqual failed. Expected a difference no greater than <-2,5815E-06> between expected value <-258,15> and actual value <-258,15>. celsius

**Comment by bluePlatinum** [comment]
Seems to me like it has gone completely mad. Even with precisionFactor = 0.1 result is still:

Test Name:	temperature_generalTest_Kelvin
Test FullName:	KMCC.Model.unitClasses.Tests.temperatureTests.temperature_generalTest_Kelvin
Test Source:	****\KMCC\UnitTests\Model\unitClasses\temperatureTests.cs : line 36
Test Outcome:	Failed
Test Duration:	0:00:00,3406438

Result StackTrace:	at KMCC.Model.unitClasses.Tests.temperatureTests.temperature_generalTest_Kelvin() in ****\KMCC\UnitTests\Model\unitClasses\temperatureTests.cs:line 50
Result Message:	Assert.AreEqual failed. Expected a difference no greater than <-25,815> between expected value <-258,15> and actual value <-258,15>. celsius

**Comment by bluePlatinum** [comment]
the problem seemed to be with negative deltas in Assert.AreEqual
(Commit 752b41388b355c58cf8e8aab4595972f571a0938)
